version: '3.4'

services:
 catalogdb:
    image: postgres

 basketdb:
    image: postgres

 orderdb:
    image: mcr.microsoft.com/mssql/server

 distributedcache:
    image: redis

 eshop.catalogapi:
    image: ${DOCKER_REGISTRY-}eshopcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/EShop.CatalogAPI/Dockerfile

 basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

 discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:




